name: itourism_mobile
description: The mobile app for itourism.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  starbase: any
  flutter_modular: ^5.0.3
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  asuka: ^2.0.1
  flutter_local_notifications: ^9.8.0+1
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  dio: ^4.0.6
  google_maps_flutter: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
